// <auto-generated />
using System;
using CormSquareSupportHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CormSquareSupportHub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CormSquareSupportHub.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OptimalCreationTime")
                        .HasColumnType("int");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Different types of documentation for knowledge management.",
                            DisplayOrder = 1,
                            Name = "Documentation",
                            OptimalCreationTime = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Short, direct answers to common questions.",
                            DisplayOrder = 1,
                            Name = "FAQs",
                            OptimalCreationTime = 2,
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Step-by-step guides for specific tasks.",
                            DisplayOrder = 2,
                            Name = "How-To Guides",
                            OptimalCreationTime = 5,
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "In-depth troubleshooting and fixes.",
                            DisplayOrder = 3,
                            Name = "Technical Solutions",
                            OptimalCreationTime = 7,
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "General guidelines and industry standards.",
                            DisplayOrder = 4,
                            Name = "Best Practices",
                            OptimalCreationTime = 4,
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Real-world problem analysis and results.",
                            DisplayOrder = 5,
                            Name = "Case Studies",
                            OptimalCreationTime = 10,
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Extensive research and validation documents.",
                            DisplayOrder = 6,
                            Name = "Whitepapers",
                            OptimalCreationTime = 14,
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Templates and methodologies for identifying root causes.",
                            DisplayOrder = 2,
                            Name = "Root Cause Analysis (RCA)",
                            OptimalCreationTime = 0
                        },
                        new
                        {
                            Id = 9,
                            Description = "Simple RCA technique by asking 'Why' five times.",
                            DisplayOrder = 1,
                            Name = "5 Whys Analysis",
                            OptimalCreationTime = 2,
                            ParentCategoryId = 8
                        },
                        new
                        {
                            Id = 10,
                            Description = "Cause-and-effect diagram for RCA.",
                            DisplayOrder = 2,
                            Name = "Fishbone Diagram (Ishikawa)",
                            OptimalCreationTime = 5,
                            ParentCategoryId = 8
                        },
                        new
                        {
                            Id = 11,
                            Description = "Proactive RCA technique identifying failure points.",
                            DisplayOrder = 3,
                            Name = "Failure Mode and Effects Analysis (FMEA)",
                            OptimalCreationTime = 7,
                            ParentCategoryId = 8
                        },
                        new
                        {
                            Id = 12,
                            Description = "Prioritizes most significant issues for RCA.",
                            DisplayOrder = 4,
                            Name = "Pareto Analysis (80/20 Rule)",
                            OptimalCreationTime = 4,
                            ParentCategoryId = 8
                        },
                        new
                        {
                            Id = 13,
                            Description = "Graphical model for identifying root causes.",
                            DisplayOrder = 5,
                            Name = "Fault Tree Analysis (FTA)",
                            OptimalCreationTime = 10,
                            ParentCategoryId = 8
                        },
                        new
                        {
                            Id = 14,
                            Description = "Structured RCA process with eight disciplines.",
                            DisplayOrder = 6,
                            Name = "8D Problem Solving",
                            OptimalCreationTime = 14,
                            ParentCategoryId = 8
                        });
                });

            modelBuilder.Entity("CormSquareSupportHub.Models.Category", b =>
                {
                    b.HasOne("CormSquareSupportHub.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("CormSquareSupportHub.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
